### ISSUE TITLE
prefer no-prototype extensions

### ISSUE THREAD

**Issue by stefanpenner** [lytics/ember-data.model-fragments#115] opened 2015-08-13 15:11 UTC
This ensures the plugin works in apps /w or without prototype extensions enabled. Please note, addons by default are to be [run with them disabled](https://github.com/rwjblue/ember-disable-prototype-extensions), so there test suite catches this issues upfront, rather then trickling downstream.

- [x] https://github.com/lytics/ember-data.model-fragments/blob/master/packages/model-fragments/lib/fragments/array/stateful.js#L43-L45
- [x] https://github.com/lytics/ember-data.model-fragments/blob/master/packages/model-fragments/lib/fragments/array/stateful.js#L118-L120
- [x] https://github.com/lytics/ember-data.model-fragments/blob/master/packages/model-fragments/lib/fragments/array/fragment.js#L119-L121

**Comment by stefanpenner** [comment] 2015-08-13 15:54
some of this may be fixed on [this long running branch](https://github.com/lytics/ember-data.model-fragments/pull/109)

**Comment by workmanw** [comment] 2015-08-14 01:21
It looks like this is resolved on the internal-model-compat branch. We can leave this open to ensure no regressions until it's merged into master.

**Comment by slindberg** [comment] 2015-08-14 19:38
Fixed in v0.4.0

**Closed by slindberg** 2015-08-14 19:38 UTC

**Comment by dguettler** [comment] 2015-10-28 08:54
is this used internally by ember-data? I can't see this anywhere in my dependencies but still running into above issue when running tests on Codeship vs my local Mac which works fine

**Comment by slindberg** [comment] 2015-10-28 15:11
> still running into above issue

What is the actual issue you are referring to? What version ED/MF are you using? If it's only in CI, try resetting the dependency cache. Also do a nombom locally to make sure packages are in sync.

**Comment by dguettler** [comment] 2015-10-29 13:05
Various versions of
> Could not find module `ember-cli-app-version/initializer-factory`

I actually get this for a bunch of different addons when running tests in Codeship. Locally everything is passing. I don't have any reference to ember-data-fragments, ember-data is at 2.1.0 and so is ember.

**Comment by dguettler** [comment] 2015-10-29 15:26
Following up on this. Turns out it was an issue when running PhantonJS 1.9 
Updating PhantomJS to 2.0.1 solved the issue
